// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9OJHNtD41JaxJtHXdHTiq0fdhFpPV1M',
    appId: '1:1047961685171:android:2b7b6ce3a638c41f5e34c6',
    messagingSenderId: '1047961685171',
    projectId: 'assei-apps-staging',
    storageBucket: 'assei-apps-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdIBr751GLJAeSVp7ewyQcr6UTi8nsno',
    appId: '1:1047961685171:ios:d8762fb6293a51c35e34c6',
    messagingSenderId: '1047961685171',
    projectId: 'assei-apps-staging',
    storageBucket: 'assei-apps-staging.firebasestorage.app',
    androidClientId: '1047961685171-1gghrb5iucrtbt0av8uk1uabmh4notnd.apps.googleusercontent.com',
    iosClientId: '1047961685171-khp0r43j4efp7nnrqt2tmutafh7p2l4r.apps.googleusercontent.com',
    iosBundleId: 'com.assessli.connector.staging',
  );

}