// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1GY1IZoLn1dgRVHE8wTxg_NIySbkBLQ',
    appId: '1:153074686205:android:c20eee800183a24717c694',
    messagingSenderId: '153074686205',
    projectId: 'assei-apps-production',
    storageBucket: 'assei-apps-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAond5sivfaeHciaJFIahkBaBcGLGd_xBk',
    appId: '1:153074686205:ios:27a3d6f472e0bade17c694',
    messagingSenderId: '153074686205',
    projectId: 'assei-apps-production',
    storageBucket: 'assei-apps-production.firebasestorage.app',
    androidClientId: '153074686205-3p4ckh1efgfpvar77d26mt4rlpf21gjh.apps.googleusercontent.com',
    iosClientId: '153074686205-b4dd3ar94sb0tgd4fir7mvacj9trcjn8.apps.googleusercontent.com',
    iosBundleId: 'com.assessli.connector',
  );

}