// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRHR8DZhqYJB8ipjxW_dImXjZk7tlUa4',
    appId: '1:799296776426:android:985e89756615be1fc88f93',
    messagingSenderId: '799296776426',
    projectId: 'assei-apps-development',
    storageBucket: 'assei-apps-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZXFLxTvs_Fln97CohPQTwVuV9clM7bg',
    appId: '1:799296776426:ios:bf24ec3f86a3b682c88f93',
    messagingSenderId: '799296776426',
    projectId: 'assei-apps-development',
    storageBucket: 'assei-apps-development.firebasestorage.app',
    androidClientId: '799296776426-2grgs7apgk378rl9m7mutuom0i1s1u1a.apps.googleusercontent.com',
    iosClientId: '799296776426-515pacq7e5u1cak96mobk6k68q1lhtel.apps.googleusercontent.com',
    iosBundleId: 'com.assessli.connector.development',
  );

}